All:
		gcc -c -o stack.o stack.c
		gcc -c -o set.o set.c
		gcc -c -o linkedList.o linkedList.c
		gcc -c -o hash_table.o hash_table.c
		gcc -c -o linked_listQ.o linked_listQ.c
		gcc -c -o queue_ll.o queue_ll.c
		gcc -c -o parser.o parser.c
		gcc -c ../lexer.c ../symboltable.c
		gcc -c -o driver.o driver.c
		gcc -c -o treeADT.o treeADT.c
		gcc -o exe stack.o set.o parser.o linkedList.o hash_table.o linked_listQ.o queue_ll.o lexer.o symboltable.o treeADT.o driver.o 